# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net


# Basic build def. No Nuget packing yet


trigger:
- master
- develop

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'Xbim.Exchange.Nuget.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 5
  minor: 0
  # creates a counter called versioncounter and seeds it at 100 and then assigns the value to a variable named buildNo.
  buildNo: $[counter('exchangeversioncounter', 100)]

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(My.buildNo)'

steps:
- task: NuGetToolInstaller@0


- task: NuGetCommand@2
  displayName: 'NuGet restore Solution'
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: nuget.config

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
